ERROR - 2024-04-14 12:18:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'CVEN', 3306, '', 0)
#1 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->index()
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#5 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#8 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->index()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#7 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#8 {main}
CRITICAL - 2024-04-14 12:18:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: testdatabase]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 APPPATH\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TestDatabase->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-04-14 12:20:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'CVEN', 3306, '', 0)
#1 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->index()
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#5 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#8 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->index()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#7 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#8 {main}
CRITICAL - 2024-04-14 12:20:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: testdatabase]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 APPPATH\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TestDatabase->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-04-14 12:37:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'CVEN', 3306, '', 0)
#1 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#5 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#8 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#7 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#8 {main}
CRITICAL - 2024-04-14 12:37:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: testdatabase]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 APPPATH\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-04-14 12:39:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'CVEN', 3306, '', 0)
#1 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#5 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#8 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#7 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#8 {main}
CRITICAL - 2024-04-14 12:39:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: testdatabase]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 APPPATH\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-04-14 12:43:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'CVEN', 3306, '', 0)
#1 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#5 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#8 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#7 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#8 {main}
CRITICAL - 2024-04-14 12:43:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: testdatabase]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 APPPATH\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-04-14 12:43:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'CVEN', 3306, '', 0)
#1 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#5 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#8 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#7 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#8 {main}
CRITICAL - 2024-04-14 12:43:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: testdatabase]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 APPPATH\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-04-14 12:43:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'CVEN', 3306, '', 0)
#1 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#5 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#8 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#7 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#8 {main}
CRITICAL - 2024-04-14 12:43:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: testdatabase]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 APPPATH\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-04-14 12:44:02 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'CVEN', 3306, '', 0)
#1 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#5 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#8 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#7 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#8 {main}
CRITICAL - 2024-04-14 12:44:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: testdatabase]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 APPPATH\Controllers\TestDatabase.php(16): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-04-14 13:17:00 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'cvenn' in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'CVENn', 3306, '', 0)
#1 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(17): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#5 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#8 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'cvenn' in C:\xampp\htdocs\projet\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\projet\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\projet\app\Controllers\TestDatabase.php(17): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projet\system\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
#3 C:\xampp\htdocs\projet\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
#4 C:\xampp\htdocs\projet\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\projet\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\projet\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#7 C:\xampp\htdocs\projet\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#8 {main}
CRITICAL - 2024-04-14 13:17:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'cvenn'
[Method: GET, Route: testdatabase]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 APPPATH\Controllers\TestDatabase.php(17): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TestDatabase->test()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDatabase))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:34 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:38 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:42 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:42 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:43 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:43 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:44 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:44 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:44 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:47 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:18:52 --> ParseError: syntax error, unexpected token "else"
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 32.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:33:08 --> ParseError: Unclosed '{' on line 6
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 21.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-04-14 18:53:28 --> ParseError: Unclosed '{' on line 8
[Method: GET, Route: signup]
in APPPATH\Controllers\SignupController.php on line 36.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\projet\\app\\Controllers\\SignupController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\SignupController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\SignupController')
 4 SYSTEMPATH\CodeIgniter.php(887): class_exists('\\App\\Controllers\\SignupController', true)
 5 SYSTEMPATH\CodeIgniter.php(496): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
